### ISSUE TITLE
Design da API

### ISSUE THREAD

**Issue by danielfireman** [viniagostini/remuneracao-dos-magistrados#2]
Criando a thread para começar o desenho da API que ficará exportada na internet. Consigo ver duas APIs bem requeridas:

1. Que será chamada pelo serviço de abertura de dados: 
     * Entrada: um link para um zip contendo um bocado de XLS e XLSx.
     * Saída:
          * Em caso de sucesso: um [pacote de dados](https://frictionlessdata.io/data-packages/) zipado.
          * Em caso de erro: uma mensage de erro o mais descritiva possível que permitirá a gente debugar e ir melhorando o serviço. Essa mensagem de erro deve conter o nome do arquivo (dentro do zip), a coluna, linha e sheet que deu o erro.

1. Que será chamada por programadores/jornalistas:
     * Entrada: um arquivo XLS ou XLSX
     * Saída: um CSV convertido (acredito que se der erro aqui, a saída de erro deve ser boa o suficiente que permita ao usuário copiar e colar o erro numa issue (além de anexar o arquivo) e a gente ter informação suficiente para relizar o debug.

**Comment by viniagostini** [comment]
Massa @danielfireman! Então quem vai reunir todos os dados de todas as planilhas então é o serviço de abertura de dados?

No caso do endpoint 1, é literalmente um link que será recebido? Ou seja, vai ser responsabilidade desse serviço baixar o que estiver nesse link para fazer o parse? Acredito que esse endpoint deva ser protegido, certo? 

No segundo caso, podemos até prover uma interface gráfica simples, com um campo para upload do arquivo e um botão de enviar, já que é um serviço voltado pra jornalistas.

**Comment by danielfireman** [comment]
> Massa @danielfireman! Então quem vai reunir todos os dados de todas as planilhas então é o serviço de abertura de dados?

Essa é minha sugestão. Ele ficaria responsável por lidar com os servidores de armazenamento externos (e.g. pcloud e datahub) e publicar os links. Você está ok com isso?

> No caso do endpoint 1, é literalmente um link que será recebido? Ou seja, vai ser responsabilidade desse serviço baixar o que estiver nesse link para fazer o parse? Acredito que esse endpoint deva ser protegido, certo?

Ponto importante. Podemos simplificar tudo deixando apenas o endpoint 2. Então vamos deixar assim: o serviço de abertura de dados ficaria responsável por juntar as respostas formando um mês e publicar o pacote de dados.

Com relação a implementação atual do serviço de parsing, ele recebe uma planilha e retorna o que? Somado a isso, como é feito a união das diversas planilhas para a análise dos dados?

> No segundo caso, podemos até prover uma interface gráfica simples, com um campo para upload do arquivo e um botão de enviar, já que é um serviço voltado pra jornalistas.

Massa. Ótima sugestão! Então teríamos uma API e uma interface que fazem basicamente a mesma coisa. É isso?

**Comment by viniagostini** [comment]
> Essa é minha sugestão. Ele ficaria responsável por lidar com os servidores de armazenamento externos (e.g. pcloud e datahub) e publicar os links. Você está ok com isso?

Massa, por mim show de bola, se eu entendi bem, a ideia é que sempre que ele detectar que tem informação nova lá no CNJ ele vai pegar esses arquivos e mandar pra cá pra que seja feito o parse, é isso mesmo?
Se for isso mesmo, o serviço de abertura de dados vai ter que ser inteligente o suficiente pra conseguir juntar a informação antiga, com a nova que ele obter.

> Ponto importante. Podemos simplificar tudo deixando apenas o endpoint 2. Então vamos deixar assim: o serviço de abertura de dados ficaria responsável por juntar as respostas formando um mês e publicar o pacote de dados.
> 
> Com relação a implementação atual do serviço de parsing, ele recebe uma planilha e retorna o que? Somado a isso, como é feito a união das diversas planilhas para a análise dos dados?

Podemos definir isso agora, por enquanto só implementei o parse das planilhas.  

Acredito que algo bem versátil seria o seguinte: 
    **Entrada:** um .zip com diversas planilhas e o formato de saída desejado (JSON ou CSV).
    **Saída:** um arquivo no formato selecionando, com todos os dados contidos na planilha, naquele formato que discutimos na lista de email.

Isso garante que possamos fazer o parse de todas as planilhas já coletadas, que serviria pro pessoal da analise de dados, e isso garante também que possamos fazer o parse sob demanda, que é o que o serviço de abertura de dados vai precisar.

**Comment by danielfireman** [comment]
> Massa, por mim show de bola, se eu entendi bem, a ideia é que sempre que ele detectar que tem informação nova lá no CNJ ele vai pegar esses arquivos e mandar pra cá pra que seja feito o parse, é isso mesmo? Se for isso mesmo, o serviço de abertura de dados vai ter que ser inteligente o suficiente pra conseguir juntar a informação antiga, com a nova que ele obter.

Exato. Cada mês vai ser um pacote de dados diferente.

> Acredito que algo bem versátil seria o seguinte:
> Entrada: um .zip com diversas planilhas e o formato de saída desejado (JSON ou CSV).
> Saída: um arquivo no formato selecionando, com todos os dados contidos na planilha, naquele formato que discutimos na lista de email

Pequena sugestão de flexibilidade na entrada:

**Entrada:** um arquivo .zip com diversas planilhas **ou** uma planilha só (xls/xlsx) **e** o formato de saída desejado (JSON ou CSV)

O que acha?

**Comment by viniagostini** [comment]
> Pequena sugestão de flexibilidade na entrada:
> 
> Entrada: um arquivo .zip com diversas planilhas ou uma planilha só (xls/xlsx) e o formato de saída desejado (JSON ou CSV)
> 
> O que acha?

Massa! Tu acha melhor um endpoint só, tratando o formato do arquivo que chega ou separar em um endpoint pra cada?


> Massa. Ótima sugestão! Então teríamos uma API e uma interface que fazem basicamente a mesma coisa. É isso?

Pois é, acho que essa interface pode ficar no serviço de abertura de dados apontando para o endpoint que está aqui. Fica mais coeso na minha opinião.

**Comment by danielfireman** [comment]
Em qui, 23 de ago de 2018 22:38, Vinicius Alencar Agostini <
notifications@github.com> escreveu:

> Pequena sugestão de flexibilidade na entrada:
>
> Entrada: um arquivo .zip com diversas planilhas ou uma planilha só
> (xls/xlsx) e o formato de saída desejado (JSON ou CSV)
>
> O que acha?
>
> Massa! Tu acha melhor um endpoint pra cada, tratando o formato do arquivo
> que chega ou separar em um endpoint pra cada?
>
Não tenho preferência, porém pensando aqui vejo que dividir pode facilitar
o monitoramento de uso. A divisão também pode deixar a validação da entrada
mais facil (principalmente relacionado a tamanhos).

> Massa. Ótima sugestão! Então teríamos uma API e uma interface que fazem
> basicamente a mesma coisa. É isso?
>
> Pois é, acho que essa interface pode ficar no serviço de abertura de dados
> apontando para o endpoint que está aqui. Fica mais coeso na minha opinião.
>
Pensando melhor aqui, não precisaremos dessa ui. O objetivo é prover tudo
já (e facilitar o usuário encontrar). O dashboard vai ser somente leitura,
o que torna as coisas mais faceis.

**Comment by viniagostini** [comment]
Massa @danielfireman com isso já tem bastante coisa pra implementar. Vou botar a mão na massa.

Quando tiver alguma coisa mais concreta a gente conversa pra testar os endpoints e pensar no deploy desse cara.

**Comment by viniagostini** [comment]
resolvido no PR #3
